#!/bin/sh

if [ $# -eq 0 ]; then
	echo "missing .tzst file argument"
	exit
fi

tar --touch -I "zstd -f" -xf $1 -C /

result=$?

if [ "$result" -eq 0 ]; then
	printf "image successfully flashed\n"
else
	printf 'error code "%d" returned' "$result"
fi
