#!/bin/sh

for p in 0 1 2 3 4
do
	if [ -d "/sys/class/net/eth$p" ]
	then
		if [ $(ethtool eth$p | grep "Link detected:" | awk '{print $3}') == yes ]
		then
			if [ $p == 0 ]
			then
				echo -n "Port $p: " > /tmp/ethernet.state
			else
				echo -n "Port $p: " >> /tmp/ethernet.state
			fi

			Duplex=$(ethtool eth$p | grep "Duplex:" | awk '{print $2'})
			echo $(ethtool eth$p | grep "Speed:" | awk '{print $2}' | sed 's,Mb\/s,'"${Duplex:0:1}"'D,g') >> /tmp/ethernet.state
		else
			echo "Port $p: DOWN" >> /tmp/ethernet.state
		fi
	else
		echo "Port $p: DOWN" >> /tmp/ethernet.state
	fi
done
