#!/bin/sh
#
# Turn off/on all led for Asus routers RT-N16, RT-N66U, RT-AC66U, RT-AC68U
#
# Version: 0.11
# Authors: Monter, Shibby, hasIPv6
#
# - changes/fixes
# Copyright (C) 2018 - 2024 by pedro
#
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/root:


. nvram_ops

# configuration
VERSION="v0.11"
# /configuration

# Send your bug report to monter[at]techlog.pl

dir=$(echo $( cd "$(dirname "$0")" ; pwd -P ))
stms=$(basename ${0})
MAKE=$(NG t_model_name | awk '{print $1}')
MODEL=$(NG t_model_name | awk '{print $2}')
USB3=$(lsusb | grep -v "Device 001" | grep "Bus 001")
USB2=$(lsusb | grep -v "Device 001" | grep "Bus 002")
LOGS="logger -s -t stealthMode"

case "$MAKE" in
	"Asus")
	;;
	*)
		$LOGS "Router Brand does not support this feature"
		exit 1
esac

case "$MODEL" in
	"RT-N16"|"RT-N66U"|"RT-AC66U"|"RT-AC68R/U")
	;;
	*)
		$LOGS "Router Model does not support this feature"
		exit 1
esac

case "$1" in
	on)
		case "$MODEL" in
			"RT-N16"|"RT-N66U"|"RT-AC66U"|"RT-AC68R/U")
				et robowr 0x00 0x18 0x1e0
			;;
			*)
				exit 99
		esac
		# strobo effect
		sleep 1

		$dir/$stms perm_on
		$LOGS "Activated"
		cru a stealthmode "*/5 * * * * $dir/$stms perm_on"
	;;
	perm_on)
		case "$MODEL" in
			"RT-N16")
				# power led
				gpio enable 1
				# unlock lan ports
				et robord 0x1 0x4 &>/dev/null
				wl -i eth1 leddc 1
			;;
			"RT-N66U"|"RT-AC66U")
				# power led
				gpio enable 12
				# usb led
				gpio enable 15
				wl -i eth1 leddc 1
				wl -i eth2 leddc 1
			;;
			"RT-AC68R/U")
				# white led at the back
				gpio enable 4
				# power led
				gpio enable 3
				# usb2 led
				gpio enable 0
				# usb3 led
				gpio enable 14
				wl -i eth1 ledbh 10 0
				wl -i eth2 ledbh 10 0
			;;
			*)
				exit 99
		esac

		case "$MODEL" in
			"RT-N16"|"RT-N66U"|"RT-AC66U"|"RT-AC68R/U")
				et robowr 0x00 0x18 0x1e0
				et robowr 0x00 0x1a 0x1e0
		;;
			*)
				exit 99
		esac
	;;
	sch_on)
		[ "${2}" != "" -a "${2}" -le 23 -a "0$(echo $2 | tr -d ' ')" -ge 0 ] 2>/dev/null && {
			[ "${3}" != "" -a "${3}" -le 59 -a "${3}" -eq "${3}" ] 2>/dev/null && SCHMIN=${3} || SCHMIN="0"
			cru a stealthsheduleon $SCHMIN $2 "* * * $dir/$stms on"
			$LOGS "Scheduled On set to $2:$(printf "%02d" $SCHMIN)"
		} || {
			$LOGS "Scheduled On error - Hour/Minutes not specified!"
			$dir/$stms
			exit 1
		}
	;;
	sch_off)
		[ "${2}" != "" -a "${2}" -le 23 -a "0$(echo $2 | tr -d ' ')" -ge 0 ] 2>/dev/null && {
			[ "${3}" != "" -a "${3}" -le 59 -a "${3}" -eq "${3}" ] 2>/dev/null && SCHMIN=${3} || SCHMIN="0"
			cru a stealthsheduleoff $SCHMIN $2 "* * * $dir/$stms off"
			$LOGS "Scheduled Off set to $2:$(printf "%02d" $SCHMIN)"
		} || {
			$LOGS "Scheduled Off error - Hour/Minutes not specified!"
			$dir/$stms
			exit 1
		}
	;;
	sch_clear)
		cru d stealthsheduleon
		cru d stealthsheduleoff
		$LOGS "Scheduler Tasks Deleted"
	;;
	clear_all)
		$dir/$stms sch_clear
		$LOGS "Complete shutdown and delete all jobs from Crontab - done"
	;;
	off)
		cru d stealthmode
		case "$MODEL" in
			"RT-N16")
				#power led
				gpio disable 1
				# unlock lan ports
				et robord 0x1 0x4 &>/dev/null
				wl -i eth1 leddc 0
			;;
			"RT-N66U"|"RT-AC66U")
				# power led
				gpio disable 12
				# usb led
				gpio disable 15
				wl -i eth1 leddc 0
				wl -i eth2 leddc 0
			;;
			"RT-AC68R/U")
				# white led at the back
				gpio disable 4
				# power led
				gpio disable 3
				[ "$USB2" != "" ] && gpio disable 0
				[ "$USB3" != "" ] && gpio disable 14
				wl -i eth1 ledbh 10 7
				wl -i eth2 ledbh 10 7
			;;
			*)
				exit 99
		esac
		case "$MODEL" in
			"RT-N16"|"RT-N66U"|"RT-AC66U"|"RT-AC68R/U")
				et robowr 0x00 0x18 0x1ff
				et robowr 0x00 0x1a 0x1ff
				# delay before repeat off commands - strobo error fix
				sleep 1
				et robowr 0x00 0x18 0x1ff
				et robowr 0x00 0x1a 0x1ff
			;;
			*)
				exit 99
		esac
		$LOGS "Deactivated"
	;;
	*)
		echo "$stms ${VERSION} by Monter"
		echo "Usage: $stms {on|off|sch_on <H> <M>|sch_off <H> <M>|sch_clear|clear_all}"
		echo
		echo " [Standard mode]"
		echo "   on | off        - enable or disable steathMode in real time"
		echo
		echo " [Scheduled mode]"
		echo "   sch_on <H> <M>  - set the hour and minutes of the scheduled enable/disable"
		echo "   sch_off <H> <M>   stealthMode in Standard mode and adding jobs to the Crontab"
		echo "                     Hour and minute time must be a numbers without any additional"
		echo "                     characters, where hour is a mandatory parameter, while not"
		echo "                     specifying an minute will assign a default 00 value"
		echo "                     These options add just the right job for Crontab, nothing more"
		echo "   sch_clear       - removes tasks from Crontab for scheduled enable/disable"
		echo "                     stealthMode function set by sch_on and sch_off switches"
		echo
		echo " [Repair / debug]"
		echo "   clear_all       - removes all jobs from Crontab and completely disables all"
		echo "                     available stealthMode modes"
		echo
		exit 1
esac
