#!/bin/sh
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/root:
cat /etc/motd; cat /proc/version; echo
echo "NVRAM"; nvram show | grep 'bytes used'; echo
echo "INTERFACES"; ifconfig; echo
echo "ROUTING TABLE"; route -n; echo; route -n -A inet6 2> /dev/null; echo
echo "ARP TABLE"; ip -4 neigh show; echo
echo "IPv6 NEIGHBOR TABLE"; ip -6 neigh show; echo
echo "IP TABLES"; echo ":filter"; iptables -nvL --line-numbers; echo; echo ":nat"; iptables -t nat -nvL --line-numbers; echo; echo ":mangle"; iptables -t mangle -nvL --line-numbers; echo
[ -x /usr/sbin/ip6tables ] && ( echo "IP6 TABLES"; echo ":filter"; ip6tables -nvL --line-numbers; echo; echo ":mangle"; ip6tables -t mangle -nvL --line-numbers; echo )
echo "NET STATS"; netstat -lnp; echo
echo "FILE SYSTEMS"; df; echo
echo "MOUNTPOINTS"; mount; echo
[ -f /proc/swaps ] && ( echo "SWAPS" && cat /proc/swaps && echo )
[ -f /proc/partitions ] && ( echo "PARTITIONS" && cat /proc/partitions && echo )
[ -f /proc/scsi/scsi ] && ( echo "SCSI DEVICES" && cat /proc/scsi/scsi && echo )
[ -f /proc/bus/usb/devices ] && ( echo "USB DEVICES" && cat /proc/bus/usb/devices && echo )
echo "ENVIRONMENT"; env; echo
echo "CPU INFO"; cat /proc/loadavg; cat /proc/cpuinfo; echo
echo "INTERRUPTS"; cat /proc/interrupts; echo
echo "MEMORY"; free; cat /proc/meminfo; echo
echo "ETH1 WIRELESS DRIVER VER"; wl -i eth1 ver; wl -i eth1 country;
echo "Valid Channels:"; wl -i eth1 channels; echo
echo "ETH2 WIRELESS DRIVER VER"; wl -i eth2 ver; wl -i eth2 country;
echo "Valid Channels:"; wl -i eth2 channels; echo
echo "LOADED MODULES"; lsmod; echo
echo "PROCESSES"; top -b -n1; echo
echo "DMESG"; dmesg; echo
