#!/bin/sh
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/root:
#
# Copyright (C) 2013 shibby
#
# - changes/fixes
# Copyright (C) 2018 - 2024 by pedro
#


. nvram_ops

# only if enabled
[ "$(NG log_wm)" -eq 1 -a "$(NG webmon_bkp)" -eq 1 ] && {

	BKP_DIR=$(NG webmon_dir)
	DATA=$(date +%Y%m%d_%H%M)
	ACTION=$1

	# remove last character from BKP_DIR if it is "/"
	[ $(echo $BKP_DIR | sed -e 's/\(^.*\)\(.$\)/\2/') == "/" ] && {
		echo $DIR | sed 's/.$//'
	}

	# create init job after webmon start
	if [ "$ACTION" == "add" ]; then
		[ "$(cru l | grep webmon | wc -l)" -eq 0 ] && {
			cru a webmon_bkp "0 0 */1 * * /usr/sbin/webmon_bkp"
			cru a webmon_tmp "59 * * * * /usr/sbin/webmon_bkp hourly"
		}

		[ -f "$BKP_DIR/webmon_recent_domains" -o -f "$BKP_DIR/webmon_recent_searches" ] && {
			echo "" &>/dev/null
		} || {
			# make first copy
			webmon_bkp hourly
		}

	# make a copy every hour
	elif [ "$ACTION" == "hourly" ]; then
		cp /proc/webmon_recent_domains $BKP_DIR/webmon_recent_domains &>/dev/null
		cp /proc/webmon_recent_searches $BKP_DIR/webmon_recent_searches &>/dev/null
	else
		LOGS="logger -t Webmon-Backup"

		# try create a file (check directory rw permission)
		touch $BKP_DIR/$DATA &>/dev/null

		# directory exists and is writable
		[ -f "$BKP_DIR/$DATA" ] && {
			rm $BKP_DIR/$DATA

			cat $BKP_DIR/webmon_recent_domains | awk '{t=$1; "date -d @\""t"\" \"+%Y-%m-%d %H:%M:%S\"" | getline d;print d"\t"$2"\t"$3 }' >> $BKP_DIR/domain-$DATA.log
			tar -czf $BKP_DIR/domain-$DATA.log.tar.gz $BKP_DIR/domain-$DATA.log &>/dev/null
			rm $BKP_DIR/domain-$DATA.log

			cat $BKP_DIR/webmon_recent_searches | awk '{t=$1; "date -d @\""t"\" \"+%Y-%m-%d %H:%M:%S\"" | getline d;print d"\t"$2"\t"$3 }' >> $BKP_DIR/search-$DATA.log
			tar -czf $BKP_DIR/search-$DATA.log.tar.gz $BKP_DIR/search-$DATA.log &>/dev/null
			rm $BKP_DIR/search-$DATA.log

			[ -f "$BKP_DIR/domain-$DATA.log.tar.gz" -a -f "$BKP_DIR/search-$DATA.log.tar.gz" ] && {
				[ "$(NG webmon_shrink)" -eq 1 ] && {
					iptables -t filter -A monitor -p tcp -m webmon --clear_search --clear_domain

					# restart firewall to reload monitor rules
					service firewall restart

					$LOGS "Backup finished. Log cleared."
				} || {
					$LOGS "Backup finished."
				}
				# make clean copy
				webmon_bkp hourly
			} || {
				$LOGS "Failed: Something goes wrong. Backup was not created!"
			}
		} || {
			$LOGS "Failed: Directory does not exist or is not writable!"
		}
	fi
}
