/*
 * quota_backup - persist xt_bandwidth quota counters across reboots
 *
 * Quota usage lives only in kernel memory, so without this a reboot hands
 * everyone a fresh allowance. Counters are read out through the bandwidth
 * match's setsockopt/getsockopt interface (libiptbwctl) and written to one
 * file per counter, mirroring how rstats/cstats persist their data.
 *
 * The set of counter ids is NOT derived from NVRAM here. rc writes the ids it
 * actually generated rules for to an id file at the same time it builds the
 * ruleset; re-deriving them by parsing quota_rules a second time would risk
 * the two disagreeing (a record rc skipped as malformed would shift every
 * later id, and counters would be restored into the wrong quota).
 *
 * Usage: quota_backup save|restore <dir> [idfile]
 *
 * Originally derived from Gargoyle's backup_quotas (gargoyle-router.com).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "ipt_bwctl.h"

#include <time.h>

#define QUOTA_IDFILE_DEFAULT	"/var/lib/quotas/ids"
#define QUOTA_MAX_WAIT_MS	5000

/*
 * Below this the wall clock has obviously not been set (no usable RTC, NTP not
 * yet synced) - years before this firmware existed. Saving then is not just
 * useless, it is destructive: the timestamp written into the backup is what a
 * later restore checks the reset interval against, so a save at ~epoch would
 * stamp the file with a 1970 time and overwrite good usage with the near-zero
 * counters that a not-yet-time-synced boot has accumulated. Refuse it. Kept in
 * step with QUOTA_CLOCK_VALID_MIN in rc/quotas.c.
 */
#define QUOTA_CLOCK_VALID_MIN	1600000000L	/* 2020-09-13 UTC */

static void quota_path_for(char *buf, size_t bufsz, const char *dir, const char *id)
{
	char safe[BANDWIDTH_MAX_ID_LENGTH + 1];
	size_t i;

	/* ids are generated by rc and shouldn't contain separators, but a stray
	 * '/' would escape the backup directory - fold it away defensively */
	strncpy(safe, id, sizeof(safe) - 1);
	safe[sizeof(safe) - 1] = '\0';
	for (i = 0; safe[i]; i++) {
		if (safe[i] == '/')
			safe[i] = '_';
	}

	snprintf(buf, bufsz, "%s/%s", dir, safe);
}

static int quota_save_one(const char *dir, char *id)
{
	char path[512];
	unsigned long num_ips = 0;
	ip_bw *data = NULL;

	if (!get_all_bandwidth_usage_for_rule_id(id, &num_ips, &data, QUOTA_MAX_WAIT_MS)) {
		/* the rule isn't loaded (quota disabled, or firewall not up yet) */
		fprintf(stderr, "quota_backup: no counter for id \"%s\"\n", id);
		return 0;
	}

	quota_path_for(path, sizeof(path), dir, id);
	if (!save_usage_to_file(data, num_ips, path)) {
		fprintf(stderr, "quota_backup: cannot write %s: %s\n", path, strerror(errno));
		free(data);
		return 0;
	}

	free(data);

	return 1;
}

static int quota_restore_one(const char *dir, char *id)
{
	char path[512];
	unsigned long num_ips = 0;
	time_t last_backup = 0;
	ip_bw *data;

	quota_path_for(path, sizeof(path), dir, id);

	data = load_usage_from_file(path, &num_ips, &last_backup);
	if (data == NULL)	/* nothing saved yet - a new quota starts at zero */
		return 0;

	/*
	 * zero_unset is 0: only the counters we have data for are touched, so a
	 * host that has used bandwidth since the rules came up isn't reset.
	 * last_backup lets the match decide whether the saved data has already
	 * aged past a reset boundary while the router was off.
	 */
	if (!set_bandwidth_usage_for_rule_id(id, 0, num_ips, last_backup, data, QUOTA_MAX_WAIT_MS)) {
		fprintf(stderr, "quota_backup: cannot restore id \"%s\"\n", id);
		free(data);
		return 0;
	}

	free(data);

	return 1;
}

int main(int argc, char **argv)
{
	const char *mode, *dir, *idfile;
	char line[BANDWIDTH_MAX_ID_LENGTH + 8];
	FILE *f;
	int saving;
	int done = 0;

	if (argc < 3) {
		fprintf(stderr, "usage: %s save|restore <dir> [idfile]\n", argv[0]);
		return 1;
	}

	mode = argv[1];
	dir = argv[2];
	idfile = (argc > 3) ? argv[3] : QUOTA_IDFILE_DEFAULT;

	if (!strcmp(mode, "save"))
		saving = 1;
	else if (!strcmp(mode, "restore"))
		saving = 0;
	else {
		fprintf(stderr, "usage: %s save|restore <dir> [idfile]\n", argv[0]);
		return 1;
	}

	/*
	 * Never write a backup with an unset clock - it would corrupt good data,
	 * see QUOTA_CLOCK_VALID_MIN. rc already defers building the rules until
	 * the clock is set, so a save this early has nothing real to write anyway;
	 * this is the last line of defence for any path that still reaches here
	 * (a stray cron tick, a shutdown during the pre-sync window).
	 */
	if (saving && time(NULL) < QUOTA_CLOCK_VALID_MIN) {
		fprintf(stderr, "quota_backup: clock not set, refusing to save\n");
		return 0;
	}

	if ((f = fopen(idfile, "r")) == NULL)
		return 0;	/* no quotas configured, nothing to do */

	if (saving)
		mkdir(dir, 0755);

	/*
	 * libiptbwctl takes the bandwidth semaphore around each get/set itself.
	 * This only registers the atexit handler that releases it if we die
	 * while holding it - without it a crash mid-save would wedge every later
	 * reader, including the GUI.
	 */
	unlock_bandwidth_semaphore_on_exit();

	while (fgets(line, sizeof(line), f) != NULL) {
		char *id = line;
		char *nl;

		while (*id == ' ' || *id == '\t')
			id++;
		if ((nl = strpbrk(id, "\r\n")) != NULL)
			*nl = '\0';
		if (*id == '\0' || *id == '#')
			continue;

		done += saving ? quota_save_one(dir, id) : quota_restore_one(dir, id);
	}
	fclose(f);

	/*
	 * Always succeed. A counter with no rule loaded, or a quota that has
	 * never been saved, is normal (newly added quota, firewall still coming
	 * up) and must not make the caller - or the cron job - look failed.
	 */
	(void)done;

	return 0;
}
